version: '3.8'
services:
  quiz-backend:
    build:
      context: ./quiz-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./quiz-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - quiz-backend
    restart: unless-stopped
